### ISSUE TITLE
Editor Config issue

### ISSUE THREAD

**Issue by thomasdegry** [istrategylabs/mo-node#19]
For `.js` and `.yml` files we have a 2 tab indent. But when using editorconfig Sublime reads it as two. Looking at the docs, changing it like such works for me:
`[*.{js,yml}]` instead of `[*.js, *.yml]`

I can create a PR if you like

**Comment by recursivefunk** [comment]
PR please sir!

**Comment by thomasdegry** [comment]
Opened!
